sqlfile: ./data/input/CSDCO.sqlite3
bucket: csdco
sparql: 
  address: localhost
  port: 8080
  database: blazegraph/namespace/csdco/sparql 

minio:
  address: localhost
  port: 9000
  accesskey: AKIAIOSFODNN7EXAMPLE
  secretkey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
